# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5.QtWidgets import QWidget, QApplication, QPushButton, QFrame, QMessageBox, QTableWidgetItem, QMainWindow
from PyQt5.QtGui import QIntValidator
from PyQt5 import QtWidgets, uic, QtCore
from PyQt5 import QtCore, QtGui, QtWidgets

from main_ui import MainWindow2
from faceRecognition import reconnaissance_facial
from TakeScreen import CaptureWindow
class MenuWindow1(QWidget):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Form1()
        self.ui.setupUi(self)

        self.ui.student_btn.clicked.connect(self.go_to_student_page)
        self.ui.camera_btn.clicked.connect(self.go_to_camera_page)
        self.ui.camera_btn_2.clicked.connect(self.go_to_screen_page)
    def go_to_student_page(self):
        self.window = MainWindow2()
        self.window.show()
    def go_to_camera_page(self):
        self.window = reconnaissance_facial()
        self.window.show()
    def go_to_screen_page(self):
        self.window = CaptureWindow()
        self.window.show()
class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(726, 440)
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(11, 25, 701, 131))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(".\\icons/logo-1.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(270, 200, 217, 45))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 310, 691, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.camera_btn = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(-1)
        self.camera_btn.setFont(font)
        self.camera_btn.setStyleSheet("    font-size: 30px;\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #f0f0f0;\n"
"    border-radius: 5px;\n"
"    background-color: #84e8f7;")
        self.camera_btn.setObjectName("camera_btn")
        self.horizontalLayout.addWidget(self.camera_btn)
        self.student_btn = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(-1)
        self.student_btn.setFont(font)
        self.student_btn.setStyleSheet("    font-size: 30px;\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #f0f0f0;\n"
"    border-radius: 5px;\n"
"    background-color: #84e8f7;")
        self.student_btn.setObjectName("student_btn")
        self.horizontalLayout.addWidget(self.student_btn)
        self.camera_btn_2 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(-1)
        self.camera_btn_2.setFont(font)
        self.camera_btn_2.setStyleSheet("    font-size: 30px;\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #f0f0f0;\n"
"    border-radius: 5px;\n"
"    background-color: #84e8f7;")
        self.camera_btn_2.setObjectName("camera_btn_2")
        self.horizontalLayout.addWidget(self.camera_btn_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "EYE GUARD"))
        self.camera_btn.setText(_translate("Form", "Camera"))
        self.student_btn.setText(_translate("Form", "Students"))
        self.camera_btn_2.setText(_translate("Form", "Take screen"))





if __name__ == '__main__':
    app = QApplication(sys.argv)

    window = MenuWindow1()

    sys.exit(app.exec())